version: 2.1

jobs:
  install_dependencies:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install python3.10
      - run: sudo apt-get install python-pip

workflows:
  main:
    jobs:
      - install_dependencies
