version: 2.1

jobs:
  install_dependencies:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: apt-get update
      - run: apt-get install python3.10

workflows:
  main:
    jobs:
      - install_dependencies
