version: 2.1

jobs:
  install_dependencies:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3.11
      - run: sudo apt-get install -y python-pip

workflows:
  main:
    jobs:
      - install_dependencies
